### ISSUE TITLE
Timed out waiting for packet header

### ISSUE THREAD

**Issue by martin-gk** [Xinyuan-LilyGO/E-Paper-watch#3]
Hi,
after succesfully testing the basic examples I uploaded a more complicated sketch to the board. Everything works fine except I cannot upload anything anymore. I always get the timed out waiting for packet header error. I've tried to use the boot button as well as the reset button. Could you offer me some assistance.

**Comment by LilyGO** [comment]
I guess it is caused by the poor contact of U2T. It is recommended that you try to read the serial port information, and press the reset button repeatedly, until the serial port returns information, which proves that the communication is normal, and then upload the program.

**Comment by LilyGO** [comment]
The problem is too long, you can open it again if necessary
